name: launchers_example
publish_to: none
description: Demonstrates how to use the launchers plugin.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  image_picker: ^0.5.0+3
  path_provider: ^0.4.1
  cupertino_icons: ^1.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  logging: ^1.0.2
  flutter_test: 
    sdk: flutter
  launchers: 
    path: /Users/ericm/sunny/player_rank/packages/launchers
flutter: 
  uses-material-design: true
