name: launchers_example
publish_to: none
description: Demonstrates how to use the launchers plugin.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  image_picker: ^0.5.0+3
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  logging: ^1.0.2
  flutter_test: 
    sdk: flutter
  launchers: 
    git: 
      url: git@github.com:SunnyApp/launchers
      ref: trippi_app
flutter: 
  uses-material-design: true
