name: launchers
description: A Flutter plugin that makes it easy to link into other apps
version: 0.4.5
homepage: https://github.com/SunnyApp/launchers

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  logging: ^0.11.4
  logging_config: ^0.4.5
  equatable: ^1.0.2
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: co.sunnyapp.launchers
    pluginClass: LaunchersPlugin

