name: launchers
description: A Flutter plugin that makes it easy to link into native apps or websites
version: 0.4.6
homepage: https://github.com/SunnyApp/launchers

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: '<3.0.0'


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.7.2
  logging: ^0.11.4
  logging_config: ^0.4.7
  equatable: ^1.2.5
  pedantic: <1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.2.3
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: co.sunnyapp.launchers
    pluginClass: LaunchersPlugin

