name: launchers
description: A Flutter plugin that makes it easy to link into native apps or websites
version: 0.5.6
homepage: https://github.com/SunnyApp/launchers

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '<3.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  logging: ^1.0.1
  logging_config: ^0.6.7+6
  equatable: ^2.0.0
  pedantic: ^1.11.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.2.3
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: co.sunnyapp.launchers
    pluginClass: LaunchersPlugin

