name: launchers
description: A Flutter plugin that makes it easy to link into other apps
version: 0.4.5
homepage: https://github.com/SunnyApp/launchers

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.1
  logging: ^0.11.3+2
#  logging_config: ^0.4.5
  logging_config:
    path: ../logging_config
  equatable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: co.sunnyapp.launchers
    pluginClass: LaunchersPlugin

